# Generated by Django 2.2.19 on 2024-04-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20240407_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='slud',
            new_name='slug',
        ),
    ]
